apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app.kubernetes.io/name: api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
